#!/bin/bash

#SBATCH --job-name=HPC_LLM_test        # Job name
#SBATCH --output=HPC_LLM_test.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --error=HPC_LLM_test.%j.err            # Error file
#SBATCH --cpus-per-task=8        # Schedule two cores
#SBATCH --gres=gpu:v100:1              # Schedule a GPU, or more with gpu:2 etc
#SBATCH --time=5:00:00          # Run time (hh:mm:ss)
#SBATCH --partition=acltr   # Run on any cores queue


#Load CUDA
module load CUDA/12.1.1

# Load python
module load Python/3.12.3-GCCcore-13.3.0
python --version
# Print out the hostname of the node the job is running on
hostname

#activate venv
source ~/envs/LLM_env/bin/activate

# Run scripts
python HPC_LLM_test.py